require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
